server:
  port: 8083
spring:
  application:
    name: INVENTORY-SERVICE
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:32768/inventorydb
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: configserver:http://localhost:9296